# Generated by Django 3.0.5 on 2020-05-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date', models.DateField(verbose_name=datetime.datetime(2020, 5, 1, 16, 33, 30, 292211))),
                ('order_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=220, unique=True)),
            ],
        ),
    ]
