# Generated by Django 3.0.5 on 2020-05-01 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=220, unique=True)),
                ('subject', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=250)),
                ('contacted', models.BooleanField(default=False, verbose_name='Contacted')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('NO', 'Choose'), ('CR', 'Card'), ('CS', 'Cash'), ('CH', 'Check')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 1, 18, 47, 39, 329311)),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
