# Generated by Django 3.0.5 on 2020-05-01 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200501_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 1, 19, 3, 7, 715269)),
        ),
    ]
