# Generated by Django 3.0.5 on 2020-05-01 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200501_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contacted',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 1, 19, 5, 10, 700080)),
        ),
    ]
