# Generated by Django 3.0.5 on 2020-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200502_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='message',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Sponsor'),
        ),
    ]
